include: ['_pages', '_css', '_scripts', '_images']

title: Doubles Damage Calculator

github: [metadata]
  
url: "https://to-metrion.github.io/dou"
  
repository: to-metrion/to-metrion.github.io/dou

description:
  
  

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

theme: jekyll-theme-cayman
